spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#     none, sql에서 테이블 드롭을 자동적으로 하게 하려면 create으로 변경하면 된다. 데이터를 계숙 유지하려고 none으로 해놓은 것.
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
